spring:
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/rental_platform_prod
    username: prod_user
    password: prod_password

app:
  jwt-secret: prod-secret-key
  jwt-expiration: 21600000