spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/rental_platform
    username: postgres
    password: 1234

app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration: 21600000