logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: jcache
      hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
      hibernate.cache.use_query_cache: true
      hibernate.cache.provider_configuration_file_resource_path: classpath:ehcache.xml
